/**
 * generated by Xtext 2.21.0
 */
package uk.ac.kcl.shiro.mydbl0304.myDbl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Create Table Instruction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.shiro.mydbl0304.myDbl.CreateTableInstruction#getTable <em>Table</em>}</li>
 *   <li>{@link uk.ac.kcl.shiro.mydbl0304.myDbl.CreateTableInstruction#getElement <em>Element</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getCreateTableInstruction()
 * @model
 * @generated
 */
public interface CreateTableInstruction extends Instructions
{
  /**
   * Returns the value of the '<em><b>Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table</em>' containment reference.
   * @see #setTable(Table)
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getCreateTableInstruction_Table()
   * @model containment="true"
   * @generated
   */
  Table getTable();

  /**
   * Sets the value of the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.CreateTableInstruction#getTable <em>Table</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Table</em>' containment reference.
   * @see #getTable()
   * @generated
   */
  void setTable(Table value);

  /**
   * Returns the value of the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' containment reference.
   * @see #setElement(CreateElementInstruction)
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getCreateTableInstruction_Element()
   * @model containment="true"
   * @generated
   */
  CreateElementInstruction getElement();

  /**
   * Sets the value of the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.CreateTableInstruction#getElement <em>Element</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element</em>' containment reference.
   * @see #getElement()
   * @generated
   */
  void setElement(CreateElementInstruction value);

} // CreateTableInstruction
