/**
 * generated by Xtext 2.21.0
 */
package uk.ac.kcl.shiro.mydbl0304.myDbl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Create Attribute Instruction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.shiro.mydbl0304.myDbl.CreateAttributeInstruction#getElement <em>Element</em>}</li>
 *   <li>{@link uk.ac.kcl.shiro.mydbl0304.myDbl.CreateAttributeInstruction#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link uk.ac.kcl.shiro.mydbl0304.myDbl.CreateAttributeInstruction#getAttributeType <em>Attribute Type</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getCreateAttributeInstruction()
 * @model
 * @generated
 */
public interface CreateAttributeInstruction extends Instructions
{
  /**
   * Returns the value of the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' containment reference.
   * @see #setElement(Element)
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getCreateAttributeInstruction_Element()
   * @model containment="true"
   * @generated
   */
  Element getElement();

  /**
   * Sets the value of the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.CreateAttributeInstruction#getElement <em>Element</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element</em>' containment reference.
   * @see #getElement()
   * @generated
   */
  void setElement(Element value);

  /**
   * Returns the value of the '<em><b>Attribute</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' containment reference.
   * @see #setAttribute(Attribute)
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getCreateAttributeInstruction_Attribute()
   * @model containment="true"
   * @generated
   */
  Attribute getAttribute();

  /**
   * Sets the value of the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.CreateAttributeInstruction#getAttribute <em>Attribute</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute</em>' containment reference.
   * @see #getAttribute()
   * @generated
   */
  void setAttribute(Attribute value);

  /**
   * Returns the value of the '<em><b>Attribute Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute Type</em>' attribute.
   * @see #setAttributeType(String)
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getCreateAttributeInstruction_AttributeType()
   * @model
   * @generated
   */
  String getAttributeType();

  /**
   * Sets the value of the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.CreateAttributeInstruction#getAttributeType <em>Attribute Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute Type</em>' attribute.
   * @see #getAttributeType()
   * @generated
   */
  void setAttributeType(String value);

} // CreateAttributeInstruction
