/**
 * generated by Xtext 2.21.0
 */
package uk.ac.kcl.shiro.mydbl0304.myDbl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Find Instruction</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getFindInstruction()
 * @model
 * @generated
 */
public interface FindInstruction extends Instructions
{
} // FindInstruction
