/**
 * generated by Xtext 2.21.0
 */
package uk.ac.kcl.shiro.mydbl0304.myDbl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Insert Instruction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.shiro.mydbl0304.myDbl.InsertInstruction#getSetAttributeInstructions <em>Set Attribute Instructions</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getInsertInstruction()
 * @model
 * @generated
 */
public interface InsertInstruction extends EObject
{
  /**
   * Returns the value of the '<em><b>Set Attribute Instructions</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.shiro.mydbl0304.myDbl.SetAttributeInstruction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Set Attribute Instructions</em>' containment reference list.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getInsertInstruction_SetAttributeInstructions()
   * @model containment="true"
   * @generated
   */
  EList<SetAttributeInstruction> getSetAttributeInstructions();

} // InsertInstruction
