/**
 * generated by Xtext 2.21.0
 */
package uk.ac.kcl.shiro.mydbl0304.myDbl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Joint Condition Unit</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.shiro.mydbl0304.myDbl.JointConditionUnit#getElementLeft <em>Element Left</em>}</li>
 *   <li>{@link uk.ac.kcl.shiro.mydbl0304.myDbl.JointConditionUnit#getJudgement <em>Judgement</em>}</li>
 *   <li>{@link uk.ac.kcl.shiro.mydbl0304.myDbl.JointConditionUnit#getElementRight <em>Element Right</em>}</li>
 *   <li>{@link uk.ac.kcl.shiro.mydbl0304.myDbl.JointConditionUnit#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getJointConditionUnit()
 * @model
 * @generated
 */
public interface JointConditionUnit extends EObject
{
  /**
   * Returns the value of the '<em><b>Element Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element Left</em>' containment reference.
   * @see #setElementLeft(AttributeOfElement)
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getJointConditionUnit_ElementLeft()
   * @model containment="true"
   * @generated
   */
  AttributeOfElement getElementLeft();

  /**
   * Sets the value of the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.JointConditionUnit#getElementLeft <em>Element Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element Left</em>' containment reference.
   * @see #getElementLeft()
   * @generated
   */
  void setElementLeft(AttributeOfElement value);

  /**
   * Returns the value of the '<em><b>Judgement</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Judgement</em>' attribute.
   * @see #setJudgement(String)
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getJointConditionUnit_Judgement()
   * @model
   * @generated
   */
  String getJudgement();

  /**
   * Sets the value of the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.JointConditionUnit#getJudgement <em>Judgement</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Judgement</em>' attribute.
   * @see #getJudgement()
   * @generated
   */
  void setJudgement(String value);

  /**
   * Returns the value of the '<em><b>Element Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element Right</em>' containment reference.
   * @see #setElementRight(AttributeOfElement)
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getJointConditionUnit_ElementRight()
   * @model containment="true"
   * @generated
   */
  AttributeOfElement getElementRight();

  /**
   * Sets the value of the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.JointConditionUnit#getElementRight <em>Element Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element Right</em>' containment reference.
   * @see #getElementRight()
   * @generated
   */
  void setElementRight(AttributeOfElement value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(BasicVar)
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getJointConditionUnit_Value()
   * @model containment="true"
   * @generated
   */
  BasicVar getValue();

  /**
   * Sets the value of the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.JointConditionUnit#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(BasicVar value);

} // JointConditionUnit
