/**
 * generated by Xtext 2.21.0
 */
package uk.ac.kcl.shiro.mydbl0304.myDbl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage
 * @generated
 */
public interface MyDblFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDblFactory eINSTANCE = uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Database</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Database</em>'.
   * @generated
   */
  Database createDatabase();

  /**
   * Returns a new object of class '<em>Instructions</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Instructions</em>'.
   * @generated
   */
  Instructions createInstructions();

  /**
   * Returns a new object of class '<em>Create Table Instruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Create Table Instruction</em>'.
   * @generated
   */
  CreateTableInstruction createCreateTableInstruction();

  /**
   * Returns a new object of class '<em>Table</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Table</em>'.
   * @generated
   */
  Table createTable();

  /**
   * Returns a new object of class '<em>Create Element Instruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Create Element Instruction</em>'.
   * @generated
   */
  CreateElementInstruction createCreateElementInstruction();

  /**
   * Returns a new object of class '<em>Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element</em>'.
   * @generated
   */
  Element createElement();

  /**
   * Returns a new object of class '<em>Create Attribute Instruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Create Attribute Instruction</em>'.
   * @generated
   */
  CreateAttributeInstruction createCreateAttributeInstruction();

  /**
   * Returns a new object of class '<em>Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribute</em>'.
   * @generated
   */
  Attribute createAttribute();

  /**
   * Returns a new object of class '<em>Basic Var</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Basic Var</em>'.
   * @generated
   */
  BasicVar createBasicVar();

  /**
   * Returns a new object of class '<em>Add Instruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Add Instruction</em>'.
   * @generated
   */
  AddInstruction createAddInstruction();

  /**
   * Returns a new object of class '<em>Insert Instruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Insert Instruction</em>'.
   * @generated
   */
  InsertInstruction createInsertInstruction();

  /**
   * Returns a new object of class '<em>Set Attribute Instruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Set Attribute Instruction</em>'.
   * @generated
   */
  SetAttributeInstruction createSetAttributeInstruction();

  /**
   * Returns a new object of class '<em>Find Instruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Find Instruction</em>'.
   * @generated
   */
  FindInstruction createFindInstruction();

  /**
   * Returns a new object of class '<em>Single Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Single Element</em>'.
   * @generated
   */
  SingleElement createSingleElement();

  /**
   * Returns a new object of class '<em>Target</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Target</em>'.
   * @generated
   */
  Target createTarget();

  /**
   * Returns a new object of class '<em>Joint Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Joint Element</em>'.
   * @generated
   */
  JointElement createJointElement();

  /**
   * Returns a new object of class '<em>Single Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Single Condition</em>'.
   * @generated
   */
  SingleCondition createSingleCondition();

  /**
   * Returns a new object of class '<em>Joint Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Joint Condition</em>'.
   * @generated
   */
  JointCondition createJointCondition();

  /**
   * Returns a new object of class '<em>Single Condition Unit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Single Condition Unit</em>'.
   * @generated
   */
  SingleConditionUnit createSingleConditionUnit();

  /**
   * Returns a new object of class '<em>Joint Condition Unit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Joint Condition Unit</em>'.
   * @generated
   */
  JointConditionUnit createJointConditionUnit();

  /**
   * Returns a new object of class '<em>Attribute Of Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribute Of Element</em>'.
   * @generated
   */
  AttributeOfElement createAttributeOfElement();

  /**
   * Returns a new object of class '<em>Delete Instruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Delete Instruction</em>'.
   * @generated
   */
  DeleteInstruction createDeleteInstruction();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MyDblPackage getMyDblPackage();

} //MyDblFactory
