/**
 * generated by Xtext 2.21.0
 */
package uk.ac.kcl.shiro.mydbl0304.myDbl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblFactory
 * @model kind="package"
 * @generated
 */
public interface MyDblPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDbl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/shiro/mydbl0304/MyDbl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDbl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDblPackage eINSTANCE = uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.DatabaseImpl <em>Database</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.DatabaseImpl
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getDatabase()
   * @generated
   */
  int DATABASE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATABASE__NAME = 0;

  /**
   * The feature id for the '<em><b>Instructions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATABASE__INSTRUCTIONS = 1;

  /**
   * The number of structural features of the '<em>Database</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATABASE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.InstructionsImpl <em>Instructions</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.InstructionsImpl
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getInstructions()
   * @generated
   */
  int INSTRUCTIONS = 1;

  /**
   * The number of structural features of the '<em>Instructions</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTIONS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.CreateTableInstructionImpl <em>Create Table Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.CreateTableInstructionImpl
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getCreateTableInstruction()
   * @generated
   */
  int CREATE_TABLE_INSTRUCTION = 2;

  /**
   * The feature id for the '<em><b>Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_TABLE_INSTRUCTION__TABLE = INSTRUCTIONS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_TABLE_INSTRUCTION__ELEMENT = INSTRUCTIONS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Create Table Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_TABLE_INSTRUCTION_FEATURE_COUNT = INSTRUCTIONS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.TableImpl <em>Table</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.TableImpl
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getTable()
   * @generated
   */
  int TABLE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Table</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.CreateElementInstructionImpl <em>Create Element Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.CreateElementInstructionImpl
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getCreateElementInstruction()
   * @generated
   */
  int CREATE_ELEMENT_INSTRUCTION = 4;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_ELEMENT_INSTRUCTION__ELEMENT = INSTRUCTIONS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Create Element Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_ELEMENT_INSTRUCTION_FEATURE_COUNT = INSTRUCTIONS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.ElementImpl
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.CreateAttributeInstructionImpl <em>Create Attribute Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.CreateAttributeInstructionImpl
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getCreateAttributeInstruction()
   * @generated
   */
  int CREATE_ATTRIBUTE_INSTRUCTION = 6;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_ATTRIBUTE_INSTRUCTION__ELEMENT = INSTRUCTIONS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Attribute</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_ATTRIBUTE_INSTRUCTION__ATTRIBUTE = INSTRUCTIONS_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Attribute Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_ATTRIBUTE_INSTRUCTION__ATTRIBUTE_TYPE = INSTRUCTIONS_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Create Attribute Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_ATTRIBUTE_INSTRUCTION_FEATURE_COUNT = INSTRUCTIONS_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.AttributeImpl
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__NAME = 0;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.BasicVarImpl <em>Basic Var</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.BasicVarImpl
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getBasicVar()
   * @generated
   */
  int BASIC_VAR = 8;

  /**
   * The feature id for the '<em><b>Integer</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASIC_VAR__INTEGER = 0;

  /**
   * The feature id for the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASIC_VAR__STRING = 1;

  /**
   * The number of structural features of the '<em>Basic Var</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASIC_VAR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.AddInstructionImpl <em>Add Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.AddInstructionImpl
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getAddInstruction()
   * @generated
   */
  int ADD_INSTRUCTION = 9;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_INSTRUCTION__ELEMENT = INSTRUCTIONS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Insert Instruction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_INSTRUCTION__INSERT_INSTRUCTION = INSTRUCTIONS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Add Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_INSTRUCTION_FEATURE_COUNT = INSTRUCTIONS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.InsertInstructionImpl <em>Insert Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.InsertInstructionImpl
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getInsertInstruction()
   * @generated
   */
  int INSERT_INSTRUCTION = 10;

  /**
   * The feature id for the '<em><b>Set Attribute Instructions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_INSTRUCTION__SET_ATTRIBUTE_INSTRUCTIONS = 0;

  /**
   * The number of structural features of the '<em>Insert Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_INSTRUCTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.SetAttributeInstructionImpl <em>Set Attribute Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.SetAttributeInstructionImpl
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getSetAttributeInstruction()
   * @generated
   */
  int SET_ATTRIBUTE_INSTRUCTION = 11;

  /**
   * The feature id for the '<em><b>Attribute</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET_ATTRIBUTE_INSTRUCTION__ATTRIBUTE = 0;

  /**
   * The feature id for the '<em><b>Attribute Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET_ATTRIBUTE_INSTRUCTION__ATTRIBUTE_VALUE = 1;

  /**
   * The number of structural features of the '<em>Set Attribute Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET_ATTRIBUTE_INSTRUCTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.FindInstructionImpl <em>Find Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.FindInstructionImpl
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getFindInstruction()
   * @generated
   */
  int FIND_INSTRUCTION = 12;

  /**
   * The number of structural features of the '<em>Find Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIND_INSTRUCTION_FEATURE_COUNT = INSTRUCTIONS_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.SingleElementImpl <em>Single Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.SingleElementImpl
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getSingleElement()
   * @generated
   */
  int SINGLE_ELEMENT = 13;

  /**
   * The feature id for the '<em><b>Targets</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_ELEMENT__TARGETS = FIND_INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_ELEMENT__ELEMENT = FIND_INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Conditions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_ELEMENT__CONDITIONS = FIND_INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Single Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_ELEMENT_FEATURE_COUNT = FIND_INSTRUCTION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.TargetImpl <em>Target</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.TargetImpl
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getTarget()
   * @generated
   */
  int TARGET = 14;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET__ATTRIBUTES = 0;

  /**
   * The number of structural features of the '<em>Target</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.JointElementImpl <em>Joint Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.JointElementImpl
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getJointElement()
   * @generated
   */
  int JOINT_ELEMENT = 15;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOINT_ELEMENT__ELEMENTS = FIND_INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Conditions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOINT_ELEMENT__CONDITIONS = FIND_INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Joint Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOINT_ELEMENT_FEATURE_COUNT = FIND_INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.SingleConditionImpl <em>Single Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.SingleConditionImpl
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getSingleCondition()
   * @generated
   */
  int SINGLE_CONDITION = 16;

  /**
   * The feature id for the '<em><b>Conditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_CONDITION__CONDITIONS = 0;

  /**
   * The number of structural features of the '<em>Single Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_CONDITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.JointConditionImpl <em>Joint Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.JointConditionImpl
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getJointCondition()
   * @generated
   */
  int JOINT_CONDITION = 17;

  /**
   * The feature id for the '<em><b>Conditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOINT_CONDITION__CONDITIONS = 0;

  /**
   * The number of structural features of the '<em>Joint Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOINT_CONDITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.SingleConditionUnitImpl <em>Single Condition Unit</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.SingleConditionUnitImpl
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getSingleConditionUnit()
   * @generated
   */
  int SINGLE_CONDITION_UNIT = 18;

  /**
   * The feature id for the '<em><b>Attribute Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_CONDITION_UNIT__ATTRIBUTE_LEFT = 0;

  /**
   * The feature id for the '<em><b>Judgement</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_CONDITION_UNIT__JUDGEMENT = 1;

  /**
   * The feature id for the '<em><b>Attribute Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_CONDITION_UNIT__ATTRIBUTE_RIGHT = 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_CONDITION_UNIT__VALUE = 3;

  /**
   * The number of structural features of the '<em>Single Condition Unit</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_CONDITION_UNIT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.JointConditionUnitImpl <em>Joint Condition Unit</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.JointConditionUnitImpl
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getJointConditionUnit()
   * @generated
   */
  int JOINT_CONDITION_UNIT = 19;

  /**
   * The feature id for the '<em><b>Element Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOINT_CONDITION_UNIT__ELEMENT_LEFT = 0;

  /**
   * The feature id for the '<em><b>Judgement</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOINT_CONDITION_UNIT__JUDGEMENT = 1;

  /**
   * The feature id for the '<em><b>Element Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOINT_CONDITION_UNIT__ELEMENT_RIGHT = 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOINT_CONDITION_UNIT__VALUE = 3;

  /**
   * The number of structural features of the '<em>Joint Condition Unit</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOINT_CONDITION_UNIT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.AttributeOfElementImpl <em>Attribute Of Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.AttributeOfElementImpl
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getAttributeOfElement()
   * @generated
   */
  int ATTRIBUTE_OF_ELEMENT = 20;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_OF_ELEMENT__ELEMENT = 0;

  /**
   * The feature id for the '<em><b>Attribute</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_OF_ELEMENT__ATTRIBUTE = 1;

  /**
   * The number of structural features of the '<em>Attribute Of Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_OF_ELEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.DeleteInstructionImpl <em>Delete Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.DeleteInstructionImpl
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getDeleteInstruction()
   * @generated
   */
  int DELETE_INSTRUCTION = 21;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE_INSTRUCTION__ELEMENT = INSTRUCTIONS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Conditions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE_INSTRUCTION__CONDITIONS = INSTRUCTIONS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Delete Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE_INSTRUCTION_FEATURE_COUNT = INSTRUCTIONS_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.Database <em>Database</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Database</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.Database
   * @generated
   */
  EClass getDatabase();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.Database#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.Database#getName()
   * @see #getDatabase()
   * @generated
   */
  EAttribute getDatabase_Name();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.Database#getInstructions <em>Instructions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Instructions</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.Database#getInstructions()
   * @see #getDatabase()
   * @generated
   */
  EReference getDatabase_Instructions();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.Instructions <em>Instructions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instructions</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.Instructions
   * @generated
   */
  EClass getInstructions();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.CreateTableInstruction <em>Create Table Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Create Table Instruction</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.CreateTableInstruction
   * @generated
   */
  EClass getCreateTableInstruction();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.CreateTableInstruction#getTable <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Table</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.CreateTableInstruction#getTable()
   * @see #getCreateTableInstruction()
   * @generated
   */
  EReference getCreateTableInstruction_Table();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.CreateTableInstruction#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.CreateTableInstruction#getElement()
   * @see #getCreateTableInstruction()
   * @generated
   */
  EReference getCreateTableInstruction_Element();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.Table <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.Table
   * @generated
   */
  EClass getTable();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.Table#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.Table#getName()
   * @see #getTable()
   * @generated
   */
  EAttribute getTable_Name();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.CreateElementInstruction <em>Create Element Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Create Element Instruction</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.CreateElementInstruction
   * @generated
   */
  EClass getCreateElementInstruction();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.CreateElementInstruction#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.CreateElementInstruction#getElement()
   * @see #getCreateElementInstruction()
   * @generated
   */
  EReference getCreateElementInstruction_Element();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.Element#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.Element#getName()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Name();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.CreateAttributeInstruction <em>Create Attribute Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Create Attribute Instruction</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.CreateAttributeInstruction
   * @generated
   */
  EClass getCreateAttributeInstruction();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.CreateAttributeInstruction#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.CreateAttributeInstruction#getElement()
   * @see #getCreateAttributeInstruction()
   * @generated
   */
  EReference getCreateAttributeInstruction_Element();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.CreateAttributeInstruction#getAttribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attribute</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.CreateAttributeInstruction#getAttribute()
   * @see #getCreateAttributeInstruction()
   * @generated
   */
  EReference getCreateAttributeInstruction_Attribute();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.CreateAttributeInstruction#getAttributeType <em>Attribute Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Attribute Type</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.CreateAttributeInstruction#getAttributeType()
   * @see #getCreateAttributeInstruction()
   * @generated
   */
  EAttribute getCreateAttributeInstruction_AttributeType();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.Attribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.Attribute#getName()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Name();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.BasicVar <em>Basic Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Basic Var</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.BasicVar
   * @generated
   */
  EClass getBasicVar();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.BasicVar#getInteger <em>Integer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Integer</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.BasicVar#getInteger()
   * @see #getBasicVar()
   * @generated
   */
  EAttribute getBasicVar_Integer();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.BasicVar#getString <em>String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.BasicVar#getString()
   * @see #getBasicVar()
   * @generated
   */
  EAttribute getBasicVar_String();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.AddInstruction <em>Add Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Add Instruction</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.AddInstruction
   * @generated
   */
  EClass getAddInstruction();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.AddInstruction#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.AddInstruction#getElement()
   * @see #getAddInstruction()
   * @generated
   */
  EReference getAddInstruction_Element();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.AddInstruction#getInsertInstruction <em>Insert Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Insert Instruction</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.AddInstruction#getInsertInstruction()
   * @see #getAddInstruction()
   * @generated
   */
  EReference getAddInstruction_InsertInstruction();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.InsertInstruction <em>Insert Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insert Instruction</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.InsertInstruction
   * @generated
   */
  EClass getInsertInstruction();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.InsertInstruction#getSetAttributeInstructions <em>Set Attribute Instructions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Set Attribute Instructions</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.InsertInstruction#getSetAttributeInstructions()
   * @see #getInsertInstruction()
   * @generated
   */
  EReference getInsertInstruction_SetAttributeInstructions();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SetAttributeInstruction <em>Set Attribute Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Set Attribute Instruction</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.SetAttributeInstruction
   * @generated
   */
  EClass getSetAttributeInstruction();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SetAttributeInstruction#getAttribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attribute</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.SetAttributeInstruction#getAttribute()
   * @see #getSetAttributeInstruction()
   * @generated
   */
  EReference getSetAttributeInstruction_Attribute();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SetAttributeInstruction#getAttributeValue <em>Attribute Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attribute Value</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.SetAttributeInstruction#getAttributeValue()
   * @see #getSetAttributeInstruction()
   * @generated
   */
  EReference getSetAttributeInstruction_AttributeValue();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.FindInstruction <em>Find Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Find Instruction</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.FindInstruction
   * @generated
   */
  EClass getFindInstruction();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleElement <em>Single Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Single Element</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.SingleElement
   * @generated
   */
  EClass getSingleElement();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleElement#getTargets <em>Targets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Targets</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.SingleElement#getTargets()
   * @see #getSingleElement()
   * @generated
   */
  EReference getSingleElement_Targets();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleElement#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.SingleElement#getElement()
   * @see #getSingleElement()
   * @generated
   */
  EReference getSingleElement_Element();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleElement#getConditions <em>Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Conditions</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.SingleElement#getConditions()
   * @see #getSingleElement()
   * @generated
   */
  EReference getSingleElement_Conditions();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.Target <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Target</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.Target
   * @generated
   */
  EClass getTarget();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.Target#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.Target#getAttributes()
   * @see #getTarget()
   * @generated
   */
  EReference getTarget_Attributes();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.JointElement <em>Joint Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Joint Element</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.JointElement
   * @generated
   */
  EClass getJointElement();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.JointElement#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.JointElement#getElements()
   * @see #getJointElement()
   * @generated
   */
  EReference getJointElement_Elements();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.JointElement#getConditions <em>Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Conditions</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.JointElement#getConditions()
   * @see #getJointElement()
   * @generated
   */
  EReference getJointElement_Conditions();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleCondition <em>Single Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Single Condition</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.SingleCondition
   * @generated
   */
  EClass getSingleCondition();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleCondition#getConditions <em>Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Conditions</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.SingleCondition#getConditions()
   * @see #getSingleCondition()
   * @generated
   */
  EReference getSingleCondition_Conditions();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.JointCondition <em>Joint Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Joint Condition</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.JointCondition
   * @generated
   */
  EClass getJointCondition();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.JointCondition#getConditions <em>Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Conditions</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.JointCondition#getConditions()
   * @see #getJointCondition()
   * @generated
   */
  EReference getJointCondition_Conditions();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleConditionUnit <em>Single Condition Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Single Condition Unit</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.SingleConditionUnit
   * @generated
   */
  EClass getSingleConditionUnit();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleConditionUnit#getAttributeLeft <em>Attribute Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attribute Left</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.SingleConditionUnit#getAttributeLeft()
   * @see #getSingleConditionUnit()
   * @generated
   */
  EReference getSingleConditionUnit_AttributeLeft();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleConditionUnit#getJudgement <em>Judgement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Judgement</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.SingleConditionUnit#getJudgement()
   * @see #getSingleConditionUnit()
   * @generated
   */
  EAttribute getSingleConditionUnit_Judgement();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleConditionUnit#getAttributeRight <em>Attribute Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attribute Right</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.SingleConditionUnit#getAttributeRight()
   * @see #getSingleConditionUnit()
   * @generated
   */
  EReference getSingleConditionUnit_AttributeRight();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleConditionUnit#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.SingleConditionUnit#getValue()
   * @see #getSingleConditionUnit()
   * @generated
   */
  EReference getSingleConditionUnit_Value();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.JointConditionUnit <em>Joint Condition Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Joint Condition Unit</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.JointConditionUnit
   * @generated
   */
  EClass getJointConditionUnit();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.JointConditionUnit#getElementLeft <em>Element Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element Left</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.JointConditionUnit#getElementLeft()
   * @see #getJointConditionUnit()
   * @generated
   */
  EReference getJointConditionUnit_ElementLeft();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.JointConditionUnit#getJudgement <em>Judgement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Judgement</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.JointConditionUnit#getJudgement()
   * @see #getJointConditionUnit()
   * @generated
   */
  EAttribute getJointConditionUnit_Judgement();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.JointConditionUnit#getElementRight <em>Element Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element Right</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.JointConditionUnit#getElementRight()
   * @see #getJointConditionUnit()
   * @generated
   */
  EReference getJointConditionUnit_ElementRight();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.JointConditionUnit#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.JointConditionUnit#getValue()
   * @see #getJointConditionUnit()
   * @generated
   */
  EReference getJointConditionUnit_Value();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.AttributeOfElement <em>Attribute Of Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute Of Element</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.AttributeOfElement
   * @generated
   */
  EClass getAttributeOfElement();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.AttributeOfElement#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.AttributeOfElement#getElement()
   * @see #getAttributeOfElement()
   * @generated
   */
  EReference getAttributeOfElement_Element();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.AttributeOfElement#getAttribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attribute</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.AttributeOfElement#getAttribute()
   * @see #getAttributeOfElement()
   * @generated
   */
  EReference getAttributeOfElement_Attribute();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.DeleteInstruction <em>Delete Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Delete Instruction</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.DeleteInstruction
   * @generated
   */
  EClass getDeleteInstruction();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.DeleteInstruction#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.DeleteInstruction#getElement()
   * @see #getDeleteInstruction()
   * @generated
   */
  EReference getDeleteInstruction_Element();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.DeleteInstruction#getConditions <em>Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Conditions</em>'.
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.DeleteInstruction#getConditions()
   * @see #getDeleteInstruction()
   * @generated
   */
  EReference getDeleteInstruction_Conditions();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDblFactory getMyDblFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.DatabaseImpl <em>Database</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.DatabaseImpl
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getDatabase()
     * @generated
     */
    EClass DATABASE = eINSTANCE.getDatabase();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATABASE__NAME = eINSTANCE.getDatabase_Name();

    /**
     * The meta object literal for the '<em><b>Instructions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATABASE__INSTRUCTIONS = eINSTANCE.getDatabase_Instructions();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.InstructionsImpl <em>Instructions</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.InstructionsImpl
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getInstructions()
     * @generated
     */
    EClass INSTRUCTIONS = eINSTANCE.getInstructions();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.CreateTableInstructionImpl <em>Create Table Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.CreateTableInstructionImpl
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getCreateTableInstruction()
     * @generated
     */
    EClass CREATE_TABLE_INSTRUCTION = eINSTANCE.getCreateTableInstruction();

    /**
     * The meta object literal for the '<em><b>Table</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CREATE_TABLE_INSTRUCTION__TABLE = eINSTANCE.getCreateTableInstruction_Table();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CREATE_TABLE_INSTRUCTION__ELEMENT = eINSTANCE.getCreateTableInstruction_Element();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.TableImpl <em>Table</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.TableImpl
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getTable()
     * @generated
     */
    EClass TABLE = eINSTANCE.getTable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABLE__NAME = eINSTANCE.getTable_Name();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.CreateElementInstructionImpl <em>Create Element Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.CreateElementInstructionImpl
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getCreateElementInstruction()
     * @generated
     */
    EClass CREATE_ELEMENT_INSTRUCTION = eINSTANCE.getCreateElementInstruction();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CREATE_ELEMENT_INSTRUCTION__ELEMENT = eINSTANCE.getCreateElementInstruction_Element();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.ElementImpl
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__NAME = eINSTANCE.getElement_Name();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.CreateAttributeInstructionImpl <em>Create Attribute Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.CreateAttributeInstructionImpl
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getCreateAttributeInstruction()
     * @generated
     */
    EClass CREATE_ATTRIBUTE_INSTRUCTION = eINSTANCE.getCreateAttributeInstruction();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CREATE_ATTRIBUTE_INSTRUCTION__ELEMENT = eINSTANCE.getCreateAttributeInstruction_Element();

    /**
     * The meta object literal for the '<em><b>Attribute</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CREATE_ATTRIBUTE_INSTRUCTION__ATTRIBUTE = eINSTANCE.getCreateAttributeInstruction_Attribute();

    /**
     * The meta object literal for the '<em><b>Attribute Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CREATE_ATTRIBUTE_INSTRUCTION__ATTRIBUTE_TYPE = eINSTANCE.getCreateAttributeInstruction_AttributeType();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.AttributeImpl
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__NAME = eINSTANCE.getAttribute_Name();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.BasicVarImpl <em>Basic Var</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.BasicVarImpl
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getBasicVar()
     * @generated
     */
    EClass BASIC_VAR = eINSTANCE.getBasicVar();

    /**
     * The meta object literal for the '<em><b>Integer</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BASIC_VAR__INTEGER = eINSTANCE.getBasicVar_Integer();

    /**
     * The meta object literal for the '<em><b>String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BASIC_VAR__STRING = eINSTANCE.getBasicVar_String();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.AddInstructionImpl <em>Add Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.AddInstructionImpl
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getAddInstruction()
     * @generated
     */
    EClass ADD_INSTRUCTION = eINSTANCE.getAddInstruction();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD_INSTRUCTION__ELEMENT = eINSTANCE.getAddInstruction_Element();

    /**
     * The meta object literal for the '<em><b>Insert Instruction</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD_INSTRUCTION__INSERT_INSTRUCTION = eINSTANCE.getAddInstruction_InsertInstruction();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.InsertInstructionImpl <em>Insert Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.InsertInstructionImpl
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getInsertInstruction()
     * @generated
     */
    EClass INSERT_INSTRUCTION = eINSTANCE.getInsertInstruction();

    /**
     * The meta object literal for the '<em><b>Set Attribute Instructions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT_INSTRUCTION__SET_ATTRIBUTE_INSTRUCTIONS = eINSTANCE.getInsertInstruction_SetAttributeInstructions();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.SetAttributeInstructionImpl <em>Set Attribute Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.SetAttributeInstructionImpl
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getSetAttributeInstruction()
     * @generated
     */
    EClass SET_ATTRIBUTE_INSTRUCTION = eINSTANCE.getSetAttributeInstruction();

    /**
     * The meta object literal for the '<em><b>Attribute</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SET_ATTRIBUTE_INSTRUCTION__ATTRIBUTE = eINSTANCE.getSetAttributeInstruction_Attribute();

    /**
     * The meta object literal for the '<em><b>Attribute Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SET_ATTRIBUTE_INSTRUCTION__ATTRIBUTE_VALUE = eINSTANCE.getSetAttributeInstruction_AttributeValue();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.FindInstructionImpl <em>Find Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.FindInstructionImpl
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getFindInstruction()
     * @generated
     */
    EClass FIND_INSTRUCTION = eINSTANCE.getFindInstruction();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.SingleElementImpl <em>Single Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.SingleElementImpl
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getSingleElement()
     * @generated
     */
    EClass SINGLE_ELEMENT = eINSTANCE.getSingleElement();

    /**
     * The meta object literal for the '<em><b>Targets</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SINGLE_ELEMENT__TARGETS = eINSTANCE.getSingleElement_Targets();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SINGLE_ELEMENT__ELEMENT = eINSTANCE.getSingleElement_Element();

    /**
     * The meta object literal for the '<em><b>Conditions</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SINGLE_ELEMENT__CONDITIONS = eINSTANCE.getSingleElement_Conditions();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.TargetImpl <em>Target</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.TargetImpl
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getTarget()
     * @generated
     */
    EClass TARGET = eINSTANCE.getTarget();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TARGET__ATTRIBUTES = eINSTANCE.getTarget_Attributes();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.JointElementImpl <em>Joint Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.JointElementImpl
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getJointElement()
     * @generated
     */
    EClass JOINT_ELEMENT = eINSTANCE.getJointElement();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOINT_ELEMENT__ELEMENTS = eINSTANCE.getJointElement_Elements();

    /**
     * The meta object literal for the '<em><b>Conditions</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOINT_ELEMENT__CONDITIONS = eINSTANCE.getJointElement_Conditions();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.SingleConditionImpl <em>Single Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.SingleConditionImpl
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getSingleCondition()
     * @generated
     */
    EClass SINGLE_CONDITION = eINSTANCE.getSingleCondition();

    /**
     * The meta object literal for the '<em><b>Conditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SINGLE_CONDITION__CONDITIONS = eINSTANCE.getSingleCondition_Conditions();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.JointConditionImpl <em>Joint Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.JointConditionImpl
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getJointCondition()
     * @generated
     */
    EClass JOINT_CONDITION = eINSTANCE.getJointCondition();

    /**
     * The meta object literal for the '<em><b>Conditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOINT_CONDITION__CONDITIONS = eINSTANCE.getJointCondition_Conditions();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.SingleConditionUnitImpl <em>Single Condition Unit</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.SingleConditionUnitImpl
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getSingleConditionUnit()
     * @generated
     */
    EClass SINGLE_CONDITION_UNIT = eINSTANCE.getSingleConditionUnit();

    /**
     * The meta object literal for the '<em><b>Attribute Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SINGLE_CONDITION_UNIT__ATTRIBUTE_LEFT = eINSTANCE.getSingleConditionUnit_AttributeLeft();

    /**
     * The meta object literal for the '<em><b>Judgement</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINGLE_CONDITION_UNIT__JUDGEMENT = eINSTANCE.getSingleConditionUnit_Judgement();

    /**
     * The meta object literal for the '<em><b>Attribute Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SINGLE_CONDITION_UNIT__ATTRIBUTE_RIGHT = eINSTANCE.getSingleConditionUnit_AttributeRight();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SINGLE_CONDITION_UNIT__VALUE = eINSTANCE.getSingleConditionUnit_Value();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.JointConditionUnitImpl <em>Joint Condition Unit</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.JointConditionUnitImpl
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getJointConditionUnit()
     * @generated
     */
    EClass JOINT_CONDITION_UNIT = eINSTANCE.getJointConditionUnit();

    /**
     * The meta object literal for the '<em><b>Element Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOINT_CONDITION_UNIT__ELEMENT_LEFT = eINSTANCE.getJointConditionUnit_ElementLeft();

    /**
     * The meta object literal for the '<em><b>Judgement</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JOINT_CONDITION_UNIT__JUDGEMENT = eINSTANCE.getJointConditionUnit_Judgement();

    /**
     * The meta object literal for the '<em><b>Element Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOINT_CONDITION_UNIT__ELEMENT_RIGHT = eINSTANCE.getJointConditionUnit_ElementRight();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOINT_CONDITION_UNIT__VALUE = eINSTANCE.getJointConditionUnit_Value();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.AttributeOfElementImpl <em>Attribute Of Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.AttributeOfElementImpl
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getAttributeOfElement()
     * @generated
     */
    EClass ATTRIBUTE_OF_ELEMENT = eINSTANCE.getAttributeOfElement();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE_OF_ELEMENT__ELEMENT = eINSTANCE.getAttributeOfElement_Element();

    /**
     * The meta object literal for the '<em><b>Attribute</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE_OF_ELEMENT__ATTRIBUTE = eINSTANCE.getAttributeOfElement_Attribute();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.DeleteInstructionImpl <em>Delete Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.DeleteInstructionImpl
     * @see uk.ac.kcl.shiro.mydbl0304.myDbl.impl.MyDblPackageImpl#getDeleteInstruction()
     * @generated
     */
    EClass DELETE_INSTRUCTION = eINSTANCE.getDeleteInstruction();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DELETE_INSTRUCTION__ELEMENT = eINSTANCE.getDeleteInstruction_Element();

    /**
     * The meta object literal for the '<em><b>Conditions</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DELETE_INSTRUCTION__CONDITIONS = eINSTANCE.getDeleteInstruction_Conditions();

  }

} //MyDblPackage
