/**
 * generated by Xtext 2.21.0
 */
package uk.ac.kcl.shiro.mydbl0304.myDbl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Set Attribute Instruction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SetAttributeInstruction#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SetAttributeInstruction#getAttributeValue <em>Attribute Value</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getSetAttributeInstruction()
 * @model
 * @generated
 */
public interface SetAttributeInstruction extends EObject
{
  /**
   * Returns the value of the '<em><b>Attribute</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' containment reference.
   * @see #setAttribute(Attribute)
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getSetAttributeInstruction_Attribute()
   * @model containment="true"
   * @generated
   */
  Attribute getAttribute();

  /**
   * Sets the value of the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SetAttributeInstruction#getAttribute <em>Attribute</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute</em>' containment reference.
   * @see #getAttribute()
   * @generated
   */
  void setAttribute(Attribute value);

  /**
   * Returns the value of the '<em><b>Attribute Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute Value</em>' containment reference.
   * @see #setAttributeValue(BasicVar)
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getSetAttributeInstruction_AttributeValue()
   * @model containment="true"
   * @generated
   */
  BasicVar getAttributeValue();

  /**
   * Sets the value of the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SetAttributeInstruction#getAttributeValue <em>Attribute Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute Value</em>' containment reference.
   * @see #getAttributeValue()
   * @generated
   */
  void setAttributeValue(BasicVar value);

} // SetAttributeInstruction
