/**
 * generated by Xtext 2.21.0
 */
package uk.ac.kcl.shiro.mydbl0304.myDbl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Single Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleElement#getTargets <em>Targets</em>}</li>
 *   <li>{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleElement#getElement <em>Element</em>}</li>
 *   <li>{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleElement#getConditions <em>Conditions</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getSingleElement()
 * @model
 * @generated
 */
public interface SingleElement extends FindInstruction
{
  /**
   * Returns the value of the '<em><b>Targets</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Targets</em>' containment reference.
   * @see #setTargets(Target)
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getSingleElement_Targets()
   * @model containment="true"
   * @generated
   */
  Target getTargets();

  /**
   * Sets the value of the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleElement#getTargets <em>Targets</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Targets</em>' containment reference.
   * @see #getTargets()
   * @generated
   */
  void setTargets(Target value);

  /**
   * Returns the value of the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' containment reference.
   * @see #setElement(Element)
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getSingleElement_Element()
   * @model containment="true"
   * @generated
   */
  Element getElement();

  /**
   * Sets the value of the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleElement#getElement <em>Element</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element</em>' containment reference.
   * @see #getElement()
   * @generated
   */
  void setElement(Element value);

  /**
   * Returns the value of the '<em><b>Conditions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions</em>' containment reference.
   * @see #setConditions(SingleCondition)
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getSingleElement_Conditions()
   * @model containment="true"
   * @generated
   */
  SingleCondition getConditions();

  /**
   * Sets the value of the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleElement#getConditions <em>Conditions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conditions</em>' containment reference.
   * @see #getConditions()
   * @generated
   */
  void setConditions(SingleCondition value);

} // SingleElement
