/**
 * generated by Xtext 2.21.0
 */
package uk.ac.kcl.shiro.mydbl0304.myDbl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Single Condition Unit</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleConditionUnit#getAttributeLeft <em>Attribute Left</em>}</li>
 *   <li>{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleConditionUnit#getJudgement <em>Judgement</em>}</li>
 *   <li>{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleConditionUnit#getAttributeRight <em>Attribute Right</em>}</li>
 *   <li>{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleConditionUnit#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getSingleConditionUnit()
 * @model
 * @generated
 */
public interface SingleConditionUnit extends EObject
{
  /**
   * Returns the value of the '<em><b>Attribute Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute Left</em>' containment reference.
   * @see #setAttributeLeft(Attribute)
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getSingleConditionUnit_AttributeLeft()
   * @model containment="true"
   * @generated
   */
  Attribute getAttributeLeft();

  /**
   * Sets the value of the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleConditionUnit#getAttributeLeft <em>Attribute Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute Left</em>' containment reference.
   * @see #getAttributeLeft()
   * @generated
   */
  void setAttributeLeft(Attribute value);

  /**
   * Returns the value of the '<em><b>Judgement</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Judgement</em>' attribute.
   * @see #setJudgement(String)
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getSingleConditionUnit_Judgement()
   * @model
   * @generated
   */
  String getJudgement();

  /**
   * Sets the value of the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleConditionUnit#getJudgement <em>Judgement</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Judgement</em>' attribute.
   * @see #getJudgement()
   * @generated
   */
  void setJudgement(String value);

  /**
   * Returns the value of the '<em><b>Attribute Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute Right</em>' containment reference.
   * @see #setAttributeRight(Attribute)
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getSingleConditionUnit_AttributeRight()
   * @model containment="true"
   * @generated
   */
  Attribute getAttributeRight();

  /**
   * Sets the value of the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleConditionUnit#getAttributeRight <em>Attribute Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute Right</em>' containment reference.
   * @see #getAttributeRight()
   * @generated
   */
  void setAttributeRight(Attribute value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(BasicVar)
   * @see uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage#getSingleConditionUnit_Value()
   * @model containment="true"
   * @generated
   */
  BasicVar getValue();

  /**
   * Sets the value of the '{@link uk.ac.kcl.shiro.mydbl0304.myDbl.SingleConditionUnit#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(BasicVar value);

} // SingleConditionUnit
