/*
 * generated by Xtext 2.21.0
 */
package uk.ac.kcl.shiro.mydbl0304.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.kcl.shiro.mydbl0304.ui.internal.Mydbl0304Activator;

public class MyDblUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Mydbl0304Activator.getInstance().getInjector("uk.ac.kcl.shiro.mydbl0304.MyDbl");
	}

}
