/*
 * generated by Xtext 2.21.0
 */
package uk.ac.kcl.shiro.mydbl0304.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyDblUiModule extends AbstractMyDblUiModule {

	public MyDblUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
