/*
 * generated by Xtext 2.21.0
 */
package uk.ac.kcl.shiro.mydbl0304.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import uk.ac.kcl.shiro.mydbl0304.ui.internal.Mydbl0304Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDblExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(Mydbl0304Activator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		Mydbl0304Activator activator = Mydbl0304Activator.getInstance();
		return activator != null ? activator.getInjector(Mydbl0304Activator.UK_AC_KCL_SHIRO_MYDBL0304_MYDBL) : null;
	}

}
