/**
 * generated by Xtext 2.21.0
 */
package uk.ac.kcl.shiro.mydbl0304.myDbl.impl;

import org.eclipse.emf.ecore.EClass;

import uk.ac.kcl.shiro.mydbl0304.myDbl.FindInstruction;
import uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Find Instruction</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FindInstructionImpl extends InstructionsImpl implements FindInstruction
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FindInstructionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDblPackage.Literals.FIND_INSTRUCTION;
  }

} //FindInstructionImpl
