/**
 * generated by Xtext 2.21.0
 */
package uk.ac.kcl.shiro.mydbl0304.myDbl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import uk.ac.kcl.shiro.mydbl0304.myDbl.Attribute;
import uk.ac.kcl.shiro.mydbl0304.myDbl.BasicVar;
import uk.ac.kcl.shiro.mydbl0304.myDbl.MyDblPackage;
import uk.ac.kcl.shiro.mydbl0304.myDbl.SingleConditionUnit;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Single Condition Unit</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.SingleConditionUnitImpl#getAttributeLeft <em>Attribute Left</em>}</li>
 *   <li>{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.SingleConditionUnitImpl#getJudgement <em>Judgement</em>}</li>
 *   <li>{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.SingleConditionUnitImpl#getAttributeRight <em>Attribute Right</em>}</li>
 *   <li>{@link uk.ac.kcl.shiro.mydbl0304.myDbl.impl.SingleConditionUnitImpl#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SingleConditionUnitImpl extends MinimalEObjectImpl.Container implements SingleConditionUnit
{
  /**
   * The cached value of the '{@link #getAttributeLeft() <em>Attribute Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttributeLeft()
   * @generated
   * @ordered
   */
  protected Attribute attributeLeft;

  /**
   * The default value of the '{@link #getJudgement() <em>Judgement</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJudgement()
   * @generated
   * @ordered
   */
  protected static final String JUDGEMENT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getJudgement() <em>Judgement</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJudgement()
   * @generated
   * @ordered
   */
  protected String judgement = JUDGEMENT_EDEFAULT;

  /**
   * The cached value of the '{@link #getAttributeRight() <em>Attribute Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttributeRight()
   * @generated
   * @ordered
   */
  protected Attribute attributeRight;

  /**
   * The cached value of the '{@link #getValue() <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected BasicVar value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SingleConditionUnitImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDblPackage.Literals.SINGLE_CONDITION_UNIT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Attribute getAttributeLeft()
  {
    return attributeLeft;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAttributeLeft(Attribute newAttributeLeft, NotificationChain msgs)
  {
    Attribute oldAttributeLeft = attributeLeft;
    attributeLeft = newAttributeLeft;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDblPackage.SINGLE_CONDITION_UNIT__ATTRIBUTE_LEFT, oldAttributeLeft, newAttributeLeft);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAttributeLeft(Attribute newAttributeLeft)
  {
    if (newAttributeLeft != attributeLeft)
    {
      NotificationChain msgs = null;
      if (attributeLeft != null)
        msgs = ((InternalEObject)attributeLeft).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDblPackage.SINGLE_CONDITION_UNIT__ATTRIBUTE_LEFT, null, msgs);
      if (newAttributeLeft != null)
        msgs = ((InternalEObject)newAttributeLeft).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDblPackage.SINGLE_CONDITION_UNIT__ATTRIBUTE_LEFT, null, msgs);
      msgs = basicSetAttributeLeft(newAttributeLeft, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDblPackage.SINGLE_CONDITION_UNIT__ATTRIBUTE_LEFT, newAttributeLeft, newAttributeLeft));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getJudgement()
  {
    return judgement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setJudgement(String newJudgement)
  {
    String oldJudgement = judgement;
    judgement = newJudgement;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDblPackage.SINGLE_CONDITION_UNIT__JUDGEMENT, oldJudgement, judgement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Attribute getAttributeRight()
  {
    return attributeRight;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAttributeRight(Attribute newAttributeRight, NotificationChain msgs)
  {
    Attribute oldAttributeRight = attributeRight;
    attributeRight = newAttributeRight;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDblPackage.SINGLE_CONDITION_UNIT__ATTRIBUTE_RIGHT, oldAttributeRight, newAttributeRight);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAttributeRight(Attribute newAttributeRight)
  {
    if (newAttributeRight != attributeRight)
    {
      NotificationChain msgs = null;
      if (attributeRight != null)
        msgs = ((InternalEObject)attributeRight).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDblPackage.SINGLE_CONDITION_UNIT__ATTRIBUTE_RIGHT, null, msgs);
      if (newAttributeRight != null)
        msgs = ((InternalEObject)newAttributeRight).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDblPackage.SINGLE_CONDITION_UNIT__ATTRIBUTE_RIGHT, null, msgs);
      msgs = basicSetAttributeRight(newAttributeRight, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDblPackage.SINGLE_CONDITION_UNIT__ATTRIBUTE_RIGHT, newAttributeRight, newAttributeRight));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BasicVar getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetValue(BasicVar newValue, NotificationChain msgs)
  {
    BasicVar oldValue = value;
    value = newValue;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDblPackage.SINGLE_CONDITION_UNIT__VALUE, oldValue, newValue);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setValue(BasicVar newValue)
  {
    if (newValue != value)
    {
      NotificationChain msgs = null;
      if (value != null)
        msgs = ((InternalEObject)value).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDblPackage.SINGLE_CONDITION_UNIT__VALUE, null, msgs);
      if (newValue != null)
        msgs = ((InternalEObject)newValue).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDblPackage.SINGLE_CONDITION_UNIT__VALUE, null, msgs);
      msgs = basicSetValue(newValue, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDblPackage.SINGLE_CONDITION_UNIT__VALUE, newValue, newValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDblPackage.SINGLE_CONDITION_UNIT__ATTRIBUTE_LEFT:
        return basicSetAttributeLeft(null, msgs);
      case MyDblPackage.SINGLE_CONDITION_UNIT__ATTRIBUTE_RIGHT:
        return basicSetAttributeRight(null, msgs);
      case MyDblPackage.SINGLE_CONDITION_UNIT__VALUE:
        return basicSetValue(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDblPackage.SINGLE_CONDITION_UNIT__ATTRIBUTE_LEFT:
        return getAttributeLeft();
      case MyDblPackage.SINGLE_CONDITION_UNIT__JUDGEMENT:
        return getJudgement();
      case MyDblPackage.SINGLE_CONDITION_UNIT__ATTRIBUTE_RIGHT:
        return getAttributeRight();
      case MyDblPackage.SINGLE_CONDITION_UNIT__VALUE:
        return getValue();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDblPackage.SINGLE_CONDITION_UNIT__ATTRIBUTE_LEFT:
        setAttributeLeft((Attribute)newValue);
        return;
      case MyDblPackage.SINGLE_CONDITION_UNIT__JUDGEMENT:
        setJudgement((String)newValue);
        return;
      case MyDblPackage.SINGLE_CONDITION_UNIT__ATTRIBUTE_RIGHT:
        setAttributeRight((Attribute)newValue);
        return;
      case MyDblPackage.SINGLE_CONDITION_UNIT__VALUE:
        setValue((BasicVar)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDblPackage.SINGLE_CONDITION_UNIT__ATTRIBUTE_LEFT:
        setAttributeLeft((Attribute)null);
        return;
      case MyDblPackage.SINGLE_CONDITION_UNIT__JUDGEMENT:
        setJudgement(JUDGEMENT_EDEFAULT);
        return;
      case MyDblPackage.SINGLE_CONDITION_UNIT__ATTRIBUTE_RIGHT:
        setAttributeRight((Attribute)null);
        return;
      case MyDblPackage.SINGLE_CONDITION_UNIT__VALUE:
        setValue((BasicVar)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDblPackage.SINGLE_CONDITION_UNIT__ATTRIBUTE_LEFT:
        return attributeLeft != null;
      case MyDblPackage.SINGLE_CONDITION_UNIT__JUDGEMENT:
        return JUDGEMENT_EDEFAULT == null ? judgement != null : !JUDGEMENT_EDEFAULT.equals(judgement);
      case MyDblPackage.SINGLE_CONDITION_UNIT__ATTRIBUTE_RIGHT:
        return attributeRight != null;
      case MyDblPackage.SINGLE_CONDITION_UNIT__VALUE:
        return value != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (judgement: ");
    result.append(judgement);
    result.append(')');
    return result.toString();
  }

} //SingleConditionUnitImpl
