/*
 * generated by Xtext 2.21.0
 */
package uk.ac.kcl.shiro.mydbl0304;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDblRuntimeModule extends AbstractMyDblRuntimeModule {
}
