/*
 * generated by Xtext 2.21.0
 */
package uk.ac.kcl.shiro.mydbl0304;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MyDblStandaloneSetup extends MyDblStandaloneSetupGenerated {

	public static void doSetup() {
		new MyDblStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
