/*
 * generated by Xtext 2.21.0
 */
package uk.ac.kcl.shiro.mydbl0304.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.kcl.shiro.mydbl0304.MyDblRuntimeModule;
import uk.ac.kcl.shiro.mydbl0304.MyDblStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MyDblIdeSetup extends MyDblStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MyDblRuntimeModule(), new MyDblIdeModule()));
	}
	
}
